/* This header is for the .Xresources options.
 * These will be set on startup by xrdb.
 */

ResourcePref resources[] = {
	{ "font",			        STRING,  &font },
    { "col_caretfgcolor",       STRING,  &col_caretfgcolor },
	{ "col_normfgcolor",        STRING,  &col_normfgcolor },
	{ "col_normbgcolor",        STRING,  &col_normbgcolor },
	{ "col_selfgcolor",         STRING,  &col_selfgcolor },
	{ "col_selbgcolor",         STRING,  &col_selbgcolor },
	{ "col_numfgcolor",         STRING,  &col_numfgcolor },
	{ "col_numbgcolor",         STRING,  &col_numbgcolor },
	{ "col_normhlfgcolor",      STRING,  &col_normhlfgcolor },
	{ "col_normhlbgcolor",      STRING,  &col_normhlbgcolor },
	{ "col_selhlfgcolor",       STRING,  &col_selhlfgcolor },
	{ "col_selhlbgcolor",       STRING,  &col_selhlbgcolor },
    { "col_bordercolor",        STRING,  &col_bordercolor },

	/* Pywal support    */
	{ "color10",        STRING,  &col_caretfgcolor },
	{ "color10",        STRING,  &col_normfgcolor },
	{ "color0",         STRING,  &col_normbgcolor },
	{ "color0",         STRING,  &col_selfgcolor },
	{ "color6",         STRING,  &col_selbgcolor },
	{ "color6",         STRING,  &col_bordercolor },
	{ "color0",         STRING,  &col_numfgcolor },
	{ "color6",         STRING,  &col_numbgcolor },
	{ "color2",         STRING,  &col_normhlbgcolor },
	{ "color3",         STRING,  &col_selhlbgcolor },
	{ "color3",         STRING,  &col_normhlfgcolor },
	{ "color0",         STRING,  &col_selhlfgcolor },

    /* sgr colors */
   	{ "col_sgrcolor0",      STRING,  &col_sgrcolor0 },
	{ "col_sgrcolor1",      STRING,  &col_sgrcolor1 },
	{ "col_sgrcolor2",      STRING,  &col_sgrcolor2 },
	{ "col_sgrcolor3",      STRING,  &col_sgrcolor3 },
	{ "col_sgrcolor4",      STRING,  &col_sgrcolor4 },
	{ "col_sgrcolor5",      STRING,  &col_sgrcolor5 },
	{ "col_sgrcolor6",      STRING,  &col_sgrcolor6 },
	{ "col_sgrcolor7",      STRING,  &col_sgrcolor7 },
	{ "col_sgrcolor8",      STRING,  &col_sgrcolor8 },
	{ "col_sgrcolor9",      STRING,  &col_sgrcolor9 },
	{ "col_sgrcolor10",     STRING,  &col_sgrcolor10 },
	{ "col_sgrcolor11",     STRING,  &col_sgrcolor11 },
	{ "col_sgrcolor12",     STRING,  &col_sgrcolor12 },
	{ "col_sgrcolor13",     STRING,  &col_sgrcolor13 },
	{ "col_sgrcolor14",     STRING,  &col_sgrcolor14 },
	{ "col_sgrcolor15",     STRING,  &col_sgrcolor15 },

    /* sgr colors */
   	{ "color0",         STRING,  &col_sgrcolor0 },
	{ "color1",         STRING,  &col_sgrcolor1 },
	{ "color2",         STRING,  &col_sgrcolor2 },
	{ "color3",         STRING,  &col_sgrcolor3 },
	{ "color4",         STRING,  &col_sgrcolor4 },
	{ "color5",         STRING,  &col_sgrcolor5 },
	{ "color6",         STRING,  &col_sgrcolor6 },
	{ "color7",         STRING,  &col_sgrcolor7 },
	{ "color8",         STRING,  &col_sgrcolor8 },
	{ "color9",         STRING,  &col_sgrcolor9 },
	{ "color10",        STRING,  &col_sgrcolor10 },
	{ "color11",        STRING,  &col_sgrcolor11 },
	{ "color12",        STRING,  &col_sgrcolor12 },
	{ "color13",        STRING,  &col_sgrcolor13 },
	{ "color14",        STRING,  &col_sgrcolor14 },
	{ "color15",        STRING,  &col_sgrcolor15 },

	{ "menuposition",   INTEGER, &menuposition },
	{ "menupaddingv",   INTEGER, &menupaddingv },
	{ "menupaddingh",   INTEGER, &menupaddingh },

    { "accuratewidth",  INTEGER, &accuratewidth },
    { "alpha",          INTEGER, &alpha },
    { "type",           INTEGER, &type },
    { "preselected",    INTEGER, &preselected },
    { "colorprompt",    INTEGER, &colorprompt },
	{ "prompt",         STRING,  &prompt },
	{ "class",          STRING,  &class },
    { "leftarrow",      STRING,  &leftarrow },
    { "rightarrow",     STRING,  &rightarrow },
	{ "bordercentered", INTEGER, &bordercentered },
	{ "borderwidth",    INTEGER, &borderwidth },
	{ "lines",          INTEGER, &lines },
	{ "columns",        INTEGER, &columns },
	{ "lineheight",     INTEGER, &lineheight },
	{ "minlineheight",  INTEGER, &minlineheight },
	{ "maxhist",        INTEGER, &maxhist },
    { "hidematchcount", INTEGER, &hidematchcount },
	{ "histnodup",      INTEGER, &histnodup },
    { "casesensitive",  INTEGER, &casesensitive },
};
