/* This header is for the .Xresources options.
 * These will be set on startup by xrdb.
 */

ResourcePref resources[] = {
	{ "font",			STRING,  &font },
    { "caretfgcolor",   STRING,  &caretfgcolor },
	{ "normfgcolor",    STRING,  &normfgcolor },
	{ "normbgcolor",    STRING,  &normbgcolor },
	{ "selfgcolor",     STRING,  &selfgcolor },
	{ "selbgcolor",     STRING,  &selbgcolor },
	{ "numfgcolor",     STRING,  &numfgcolor },
	{ "numbgcolor",     STRING,  &numbgcolor },
	{ "normhlfgcolor",  STRING,  &normhlfgcolor },
	{ "normhlbgcolor",  STRING,  &normhlbgcolor },
	{ "selhlfgcolor",   STRING,  &selhlfgcolor },
	{ "selhlbgcolor",   STRING,  &selhlbgcolor },

	/* Pywal support    */
	{ "color0",         STRING,  &caretfgcolor },
	{ "color10",        STRING,  &normfgcolor },
	{ "color0",         STRING,  &normbgcolor },
	{ "color0",         STRING,  &selfgcolor },
	{ "color6",         STRING,  &selbgcolor },
	{ "color0",         STRING,  &numfgcolor },
	{ "color6",         STRING,  &numbgcolor },
	{ "color2",         STRING,  &normhlbgcolor },
	{ "color3",         STRING,  &selhlbgcolor },
	{ "color3",         STRING,  &normhlfgcolor },
	{ "color0",         STRING,  &selhlfgcolor },

    /* sgr colors */
   	{ "sgrcolor0",      STRING,  &sgrcolor0 },
	{ "sgrcolor1",      STRING,  &sgrcolor1 },
	{ "sgrcolor2",      STRING,  &sgrcolor2 },
	{ "sgrcolor3",      STRING,  &sgrcolor3 },
	{ "sgrcolor4",      STRING,  &sgrcolor4 },
	{ "sgrcolor5",      STRING,  &sgrcolor5 },
	{ "sgrcolor6",      STRING,  &sgrcolor6 },
	{ "sgrcolor7",      STRING,  &sgrcolor7 },
	{ "sgrcolor8",      STRING,  &sgrcolor8 },
	{ "sgrcolor9",      STRING,  &sgrcolor9 },
	{ "sgrcolor10",     STRING,  &sgrcolor10 },
	{ "sgrcolor11",     STRING,  &sgrcolor11 },
	{ "sgrcolor12",     STRING,  &sgrcolor12 },
	{ "sgrcolor13",     STRING,  &sgrcolor13 },
	{ "sgrcolor14",     STRING,  &sgrcolor14 },
	{ "sgrcolor15",     STRING,  &sgrcolor15 },

    /* sgr colors */
   	{ "color0",         STRING,  &sgrcolor0 },
	{ "color1",         STRING,  &sgrcolor1 },
	{ "color2",         STRING,  &sgrcolor2 },
	{ "color3",         STRING,  &sgrcolor3 },
	{ "color4",         STRING,  &sgrcolor4 },
	{ "color5",         STRING,  &sgrcolor5 },
	{ "color6",         STRING,  &sgrcolor6 },
	{ "color7",         STRING,  &sgrcolor7 },
	{ "color8",         STRING,  &sgrcolor8 },
	{ "color9",         STRING,  &sgrcolor9 },
	{ "color10",        STRING,  &sgrcolor10 },
	{ "color11",        STRING,  &sgrcolor11 },
	{ "color12",        STRING,  &sgrcolor12 },
	{ "color13",        STRING,  &sgrcolor13 },
	{ "color14",        STRING,  &sgrcolor14 },
	{ "color15",        STRING,  &sgrcolor15 },

	{ "menuposition",   INTEGER, &menuposition },
	{ "menupaddingv",   INTEGER, &menupaddingv },
	{ "menupaddingh",   INTEGER, &menupaddingh },

    { "alpha",          INTEGER, &alpha },
    { "type",           INTEGER, &type },
    { "preselected",    INTEGER, &preselected },
    { "colorprompt",    INTEGER, &colorprompt },
	{ "prompt",         STRING,  &prompt },
	{ "class",          STRING,  &class },
    { "leftarrow",      STRING,  &leftarrow },
    { "rightarrow",     STRING,  &rightarrow },
	{ "bordercentered", INTEGER, &bordercentered },
	{ "borderwidth",    INTEGER, &borderwidth },
	{ "lines",          INTEGER, &lines },
	{ "columns",        INTEGER, &columns },
	{ "lineheight",     INTEGER, &lineheight },
	{ "minlineheight",  INTEGER, &minlineheight },
	{ "maxhist",        INTEGER, &maxhist },
    { "hidematchcount", INTEGER, &hidematchcount },
	{ "histnodup",      INTEGER, &histnodup },
    { "casesensitive",  INTEGER, &casesensitive },
};
