/* color schemes */
enum { SchemeLArrow,
       SchemeRArrow,
       SchemeItemNorm,
       SchemeItemSel,
       SchemeMenu,
       SchemeInput,
       SchemePrompt,
       SchemeNormHighlight,
       SchemeSelHighlight,
       SchemeCaret,
       SchemeNumber,
       SchemeMode,
       SchemeBorder,
       SchemeLast,
};
